ProductManagement/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using ProductManagement.Entity;
using ProductManagement.Interface;
using ProductManagement.ViewModels;

namespace ProductManagement.Controllers
{
    public class BranchController : Controller
    {
        private IBranchRepo _branchRepo;
        static string ResponseMessage = "";
        public BranchController(IBranchRepo branchRepo)
        {
            _branchRepo = branchRepo;
        }


        public IActionResult Index()
        {
            BranchVM branchViewModel = new BranchVM()
            {
                Branches = _branchRepo.GetBranches(),
                PageTitle = "Branch Details"
            };

            if (ResponseMessage.Length > 0)
            {
                ViewBag.Message = ResponseMessage;
                ResponseMessage = "";
            }
            else
            {
                ViewBag.Message = "";
            }
            return View(branchViewModel);
        }


        public ViewResult Update(int Id)
        {
            BranchVM branchViewModel = new BranchVM()
            {
                Branch = _branchRepo.GeBranch(Id),
                PageTitle = "Edit Employee"
            };

            return View(branchViewModel);

        }

        [HttpPost]
        public ActionResult Update(Branch branch)
        {
            if (ModelState.IsValid)
            {

                ResponseMessage = _branchRepo.SaveBranch(branch);
                
                return RedirectToAction("Index");
            }
            BranchVM branchViewModel = new BranchVM()
            {
                Branch = _branchRepo.GeBranch(branch.BranchId),
                PageTitle = "Edit Employee"
            };

            return View(branchViewModel);

        }


        [HttpPost]
        public ActionResult Create(Branch branch)
        {
            if (ModelState.IsValid)
            {
                ResponseMessage = _branchRepo.AddBranch(branch);
                return RedirectToAction("Index");

            }
            BranchVM branchViewModel = new BranchVM()
            {
                Branch = branch,
                PageTitle = "Create Employee"
            };
            return View(branchViewModel);


           
        }
        public ViewResult Create()
        {
            BranchVM branchViewModel = new BranchVM()
            {
               // Branch = _branchRepo.AddBranch(branch),
                PageTitle = "Edit Employee"
            };

            return View(branchViewModel);

        }

        //public ActionResult Delete(int BranchId)
        //{
        //    int id = _branchRepo.DeleteBranch(BranchId);
        //    if (id > 0)
        //    {
        //        ResponseMessage = "Data successfully deleted.";
        //    }
        //    return RedirectToAction("Index");

        //}
        public ActionResult Delete(int Id)
        {
            string id = _branchRepo.DeleteBranch(Id);
           // if (id > 0)
            //{
                ResponseMessage = "Data successfully deleted.";
            //}
            return RedirectToAction("Index");

        }



    }
}

ProductManagement/Views/Branch/Create.cshtml
@model BranchVM
@{
    ViewBag.Title = "Branch List";
}

<!--PAGE CONTENT -->


<div class="inner">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">@Model.PageTitle</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Branch Information
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <form role="form" asp-action="Create" asp-controller="Branch" method="post">
                                <div class="form-group col-lg-4">
                                    <label>BranchName</label>
                                    <input class="form-control" asp-for="Branch.BranchName">
                                    <span class="alert-danger" asp-validation-for="Branch.BranchName"></span>

                                </div>
                                <div class="form-group col-lg-4">
                                    <label>BranchDesc</label>
                                    <input class="form-control" asp-for="Branch.BranchDesc">
                                    
                                </div>
                                <div class="form-group col-lg-4">
                                    <label>Branch Status</label>
                                    <select class="form-control" asp-for="Branch.BranchStatus" asp-items="Html.GetEnumSelectList<Status>()"></select>
                                </div>



                                <div class="form-group col-lg-4">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <button type="reset" class="btn btn-warning">Reset</button>
                                    <a asp-controller="Branch"
                                       asp-action="Index" class="btn btn-danger">Cancel</a>

                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

</div>





<!--END PAGE CONTENT -->

ProductManagement/Views/Branch/Index.cshtml
@model BranchVM
@{
    ViewBag.Title = "Branch List";
}


<div class="inner">
    <div class="row">
        <div class="col-lg-12">


            <h2>@Model.PageTitle</h2>



        </div>
    </div>

    <hr />


    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading text-right">
                    <a asp-controller="Branch"
                       asp-action="Create"><i class="icon-plus-sign"></i>Add New</a>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">

                            <thead>
                                <tr>
                                    <th>SNo</th>
                                    <th>Name</th>
                                    <th>Desc</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{

                                    var i = 1;
                                }


                                @foreach (var branch in Model.Branches)
                                {
                                    <tr>
                                        <td>@(i++)</td>
                                        <td>@branch.BranchName</td>
                                        <td>@branch.BranchDesc</td>
                                        <td>@branch.BranchStatus</td>
                                        <td>
                                            <a asp-controller="Branch"
                                               asp-action="Update" asp-route-id="@branch.BranchId"><i class="icon-edit"></i></a>
                                            <a asp-controller="Branch"
                                               asp-action="Delete" asp-route-id="@branch.BranchId" onclick="return confirm('Are you sure you want to delete this?')"><i class="icon-trash"></i></a>
                                        </td>
                                    </tr>

                                }
                            </tbody>
                        </table>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="notificationModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Message</h4>
            </div>
            <div class="modal-body">
                @ViewBag.Message
            </div>

        </div>
    </div>
</div>
@section Scripts{
    <!-- PAGE LEVEL SCRIPTS -->
    <script src="~/assets/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="~/assets/plugins/dataTables/dataTables.bootstrap.js"></script>
    <link href="~/assets/plugins/gritter/css/jquery.gritter.css" rel="stylesheet" />
    <script src="~/assets/plugins/gritter/js/jquery.gritter.js"></script>
    <script>
        $(document).ready(function () {
            $('#dataTables-example').dataTable();
        });
    </script>
    @if (ViewBag.Message != "")
    {

        <script>
            $(function () {
                $.gritter.add({
                    // (string | mandatory) the heading of the notification
                    title: 'Information',
                    // (string | mandatory) the text inside the notification
                    text:  '@ViewBag.Message'
                });
                return false;
            });
        </script>
    }


    <!-- END PAGE LEVEL SCRIPTS -->
}

ProductManagement/Views/Branch/Update.cshtml
@model BranchVM
@{
    ViewBag.Title = "Branch List";
}

<!--PAGE CONTENT -->


<div class="inner">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"> @Model.PageTitle</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Branch Information
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <form role="form" asp-action="Update" asp-controller="Branch" method="post">
                                <div class="form-group col-lg-4">
                                    <label>Branch Name</label>
                                    <input class="form-control" asp-for="@Model.Branch.BranchName">
                                    <span class="alert-danger" asp-validation-for="@Model.Branch.BranchName"></span>
                                    <input class="form-control" type="hidden" asp-for="@Model.Branch.BranchId">
                                </div>
                                <div class="form-group col-lg-4">
                                    <label>Branch Desc</label>
                                    <input class="form-control" asp-for="@Model.Branch.BranchDesc">
                                    
                                </div>
                                <div class="form-group col-lg-4">
                                    <label>Branch Status</label>
                                    <select class="form-control" asp-for="Branch.BranchStatus" asp-items="Html.GetEnumSelectList<Status>()"></select>
                               </div>

                                


                                    <div class="form-group col-lg-4">
                                        <button type="submit" class="btn btn-primary">Submit </button>
                                        <button type="reset" class="btn btn-warning">Reset </button>
                                        <a asp-controller="Branch"
                                           asp-action="Index" class="btn btn-danger">Cancel</a>
                                    </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

</div>





<!--END PAGE CONTENT -->